#!/usr/bin/env bash
# Regenerate demo/css/style.css by concatenating the modular CSS
# under public/css/ in the same order as public/css/style.css's
# @import manifest. The demo ships as a flat single-file stylesheet
# so it can be opened directly with file:// URLs (no @import resolution
# needed and no extra HTTP round-trips for a static preview).
#
# Run from the repo root after touching any file under public/css/:
#   ./demo/css/build.sh
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
src_dir="$repo_root/public/css"
out_file="$repo_root/demo/css/style.css"

# Cascade order — keep in lockstep with public/css/style.css.
modules=(
    base/core.css
    base/layout.css
    components/roles.css
    components/cards.css
    components/buttons.css
    components/forms.css
    components/tables.css
    components/badges.css
    components/toasts.css
    components/modals.css
    pages/dashboard.css
    pages/schedules.css
    pages/login.css
    components/filters-pagination-states.css
    components/pickers.css
    utilities/scrollbar-utility.css
    utilities/responsive.css
    utilities/print.css
    components/tables-scalable.css
    components/pickers-toolbar.css
    components/misc.css
    pages/extras.css
    pages/data-tables.css
    components/data-table-enhancements.css
    base/theme-light.css
    pages/card-lookup.css
    pages/tickets.css
    pages/analytics.css
    pages/performance.css
    components/clickable.css
    components/deep-link.css
    components/polish-controls.css
    pages/dashboard/pulse.css
    pages/dashboard/stat-cards.css
    pages/dashboard/top-games.css
    pages/dashboard/live-feed.css
    pages/dashboard/status-pills.css
    pages/dashboard/active-overrides.css
    pages/dashboard/motion.css
    pages/kiosks.css
    pages/dashboard/footer.css
    polish.css
)

{
    cat <<'HEADER'
/* ============================================
   Castle Fun Center — Management System
   ============================================
   AUTOGENERATED for the demo: this is a flat
   concatenation of public/css/style.css's @import
   manifest, in cascade order. Regenerate after
   touching any of the modular source files (see
   demo/README.md for the one-line command).
   ============================================ */

HEADER
    for f in "${modules[@]}"; do
        printf '\n/* === source: public/css/%s === */\n' "$f"
        cat "$src_dir/$f"
    done
} > "$out_file"

echo "Wrote $out_file ($(wc -l < "$out_file") lines, $(wc -c < "$out_file") bytes)"
